<a href="https://colab.research.google.com/github/YasuharuSuzuki/26_programing2/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03_機械学習

### 用語の理解を問う問題
- 以下の問題について、正解となる選択肢を出力してください
※4択問題は1回目の回答のみが有効です。何度も提出することは出来ませんので、ご注意ください。

---
---
---

### 🎲 四択問題16 回帰モデル (3点)
- 次のうち、回帰モデルの特徴として最も適切なものを選べ  
   📕 1. カテゴリーを予測する  
   📗 2. 連続的な数値を予測する  
   📘 3. データをグループ分けする  
   📙 4. パターンを認識する

In [1]:
# 正解を出力してください
print('')

In [ ]:
#@title 送信処理用共通プログラム（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown 解答の送信に必要です。（中身は絶対に修正しないでください）

import os
os.makedirs(".client/python", exist_ok=True)  # 隠しフォルダを作成
!wget -q https://raw.githubusercontent.com/YasuharuSuzuki/26_programing2/main/91_notebook_client/src/setup.sh -O .client/setup.sh   # 外部コードをダウンロードして隠しフォルダに配置
!chmod +x ./.client/setup.sh
!bash ./.client/setup.sh # 実行

# sandbox実行用
# os.symlink("../../src", ".client", target_is_directory=True)
# !bash ./sandbox_setup.sh # 実行

# モジュールの初期化
exec(open('.client/client_setup.py').read())

# ノートブック固有の設定
NOTEBOOK_PATH = "16_期末テスト/03_機械学習.ipynb"
set_notebook_config(NOTEBOOK_PATH)

In [ ]:
#@title 問16 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=16, button_name="四択問題"))

---
---
---

### 🎲 四択問題17 指標 (3点)
- 予測値と実際の値の二乗誤差の平均を取り、さらに平方根を取った指標は何と呼ばれますか？  
   📕 1. 平均絶対誤差（MAE）  
   📗 2. 平均二乗誤差（MSE）  
   📘 3. 二乗平均平方根誤差（RMSE）  
   📙 4. R-squared（決定係数）

In [2]:
# 正解を出力してください
print('')

In [ ]:
#@title 問17 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=17, button_name="四択問題"))

---
---
---

### 🎲 四択問題18 分類問題 (3点)
- 次のうち、分類問題の例として最も適切なものを選べ  
   📕 1. 住宅価格の予測  
   📗 2. 株価の予測  
   📘 3. 顧客の購買量の予測  
   📙 4. 顧客が商品を購入するかどうかの予測

In [3]:
# 正解を出力してください
print('')

In [ ]:
#@title 問18 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=18, button_name="四択問題"))

---
---
---

## 👊 プログラムを書く問題
- penguinのデータセットを使って、モデルの作成、評価を行ってください。

### 🐧 ༘ Penguinのデータセット
- ペンギンの生息地、くちばしの大きさ等から、種別を推測するデータセットです。
- `data/penguins.csv` のデータを読み込んで処理して行きましょう。
- 各列の名称と内容は以下の通りです。([Githubの情報](https://github.com/allisonhorst/palmerpenguins?tab=readme-ov-file#about-the-data)から抜粋)

| Variable | Definition | Key |
| --- | --- | --- | 
| species | penguin species | [Chinstrap, Adélie, or Gentoo](https://github.com/allisonhorst/palmerpenguins?tab=readme-ov-file#meet-the-palmer-penguins) |
| island | island name in the Palmer Archipelago (Antarctica) | Dream, Torgersen, or Biscoe |
| bill_length_mm | [the culmen(bill) length (mm)](https://github.com/allisonhorst/palmerpenguins?tab=readme-ov-file#bill-dimensions) |  |
| bill_depth_mm | [the culmen(bill) depth (mm)](https://github.com/allisonhorst/palmerpenguins?tab=readme-ov-file#bill-dimensions) |
| flipper_length_mm | flipper length (mm) | |
| body_mass_g | body mass (g) |
| sex | penguin sex | |

### 🤖 問19 モデルの作成 (9点)
- データセットを読み込み、欠損値の処理やカテゴリカル変数の対策を行って、モデルを作成してみましょう
  - データセットの読み込み（02pandas.ipynbと同じプログラムで大丈夫です）
  - 欠損値の対策（02pandas.ipynbと同じプログラムで大丈夫です）
  - カテゴリカル変数の対策
  - 説明変数と目的変数に分ける
  - モデルを学習する（学習に使用するモデルは何でも良いです。例：SVC、RandomForestClassifierなど）

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [4]:
# ライブラリのimport
import pandas as pd # pandasモジュールを読み込む（データ分析ライブラリ）
import numpy as np # NumPyモジュールを読み込む（数値演算ライブラリ）
import matplotlib.pyplot as plt # 可視化ライブラリ
import seaborn as sns # Seabornモジュールを読み込む（可視化ライブラリ。pairplotなど多くのデータ分析情報をplotするのに向いている）

from sklearn.preprocessing import LabelEncoder # 文字データを数字に置換するクラス（後述）
from sklearn.model_selection import train_test_split # scikit-learnの訓練データ / テストデータ 分割関数
from sklearn import metrics # scikit-learnの精度算出用ライブラリ
from sklearn import svm # scikit-learnのSVM(サポートベクターマシン)
from sklearn.ensemble import RandomForestClassifier # scikit-learnのRandomForest(ランダムフォレスト)

from mpl_toolkits.axes_grid1 import Divider, Size # matplotlib 領域修正用クラス
from mpl_toolkits.axes_grid1.mpl_axes import Axes # matplotlib 領域修正用クラス

In [ ]:
# drive.mount()を使用してGoogleDriveをMount
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# os.chdir()を使用してカレントディレクトリを変更。作成したショーットカット名を使ってパスを指定します。
import os
os.chdir('/content/drive/MyDrive/＜作成したショートカット名＞')

In [6]:
# データファイルパス定義
PENGUIN_CSV = "./data/penguins.csv"

In [ ]:
# read_csvを使ってcsvを読み込みます

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [ ]:
# 欠損値対策1
# SexがNoneの個体に'Unkown'を入れておく

# 欠損値対策2
# bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g にもわずかですが欠損値が見られたため、削除しておきます

In [ ]:
# 欠損値が無くなったことを確認しましょう

<class 'pandas.core.frame.DataFrame'>
Index: 342 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            342 non-null    object
 1   island             342 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                342 non-null    object
dtypes: float64(4), object(3)
memory usage: 21.4+ KB

In [ ]:
# カテゴリカル変数の対策

species
0    151
2    123
1     68
Name: count, dtype: int64
island
0    167
1    124
2     51
Name: count, dtype: int64
sex
1    168
0    165
2      9
Name: count, dtype: int64

In [ ]:
# 説明変数と目的変数に分ける

In [ ]:
# 訓練データとテストデータに分割する

In [ ]:
# 学習する

SVC()

In [ ]:
#@title 問19 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=19, button_name="問"))

---
---
---

### 🧐　問20 モデルの評価 (12点)
- 以下のいずれかの評価を少なくとも２つ行って、それぞれに最低１つの簡単な考察をつけてみましょう
  - 正答率と誤った個数を算出する
  - classification reportを作成する
  - 混合行列(confusion matrix)を表示する
  - FeatureImportanceを表示する(決定木系のモデルでしか使用できません)

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# モデルの評価１

# 考察：こちらにソースコメントで考察を記述して下さい。
# コードセルに書かれたコメントを読み取って採点していますので、マークダウンには書かないでください。

正答率 = 0.7864077669902912
誤った個数：22

In [ ]:
# モデルの評価２

# 考察：こちらにソースコメントで考察を記述して下さい。
# コードセルに書かれたコメントを読み取って採点していますので、マークダウンには書かないでください。

classification report

/mnt/d/user/yasubei/project/okikokudai/24年度/03プログラミングII(2024前期)/90リポジトリ/24_programing2/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/mnt/d/user/yasubei/project/okikokudai/24年度/03プログラミングII(2024前期)/90リポジトリ/24_programing2/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/mnt/d/user/yasubei/project/okikokudai/24年度/03プログラミングII(2024前期)/90リポジトリ/24_programing2/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score     support
0              0.703125  1.000000  0.825688   45.000000
1              0.000000  0.000000  0.000000   21.000000
2              0.923077  0.972973  0.947368   37.000000
accuracy       0.786408  0.786408  0.786408    0.786408
macro avg      0.542067  0.657658  0.591019  103.000000
weighted avg   0.638781  0.786408  0.701054  103.000000

In [ ]:
#@title 問20 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=20, button_name="問"))