<a href="https://colab.research.google.com/github/YasuharuSuzuki/26_programing2/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 𖠌 Section 13 機械学習(分類)
# 01_SVCによる分類モデルの学習
scikit-learnを使って機械学習モデルを作ってみましょう。

## 🌌 scikit-learnとは
<img src="https://raw.githubusercontent.com/scikit-learn/scikit-learn/main/doc/logos/scikit-learn-logo.png">

- Scikit-learnはNumPyやSciPyといった数値演算、数値解析ライブラリと組み合わせて使うことが出来る機械学習ライブラリです。
- Scikit-learnはSVMやRandomForest、Gradient Boosting、k-NN、DBSCANといった非常に多くの機械学習アルゴリズムに対応しており、それらを使って分類、回帰、クラスタリングといった様々な機械学習を行うことが可能です。

### 🏅 Scikit-learnを使うメリット
- 一貫性: Scikit-learnのすべてのクラスは、共通のメソッドを持っています。これにより、学習コストを抑えることが可能です。
- 豊富な機能: 分類、回帰、クラスタリング、次元削減、モデル選択など、非常に多くの機械学習タスクをサポートしています。
- 高度なドキュメンテーション: Scikit-learnの公式ウェブサイトには、各モデルの詳細な説明や、どのように実装すればよいかの具体的なガイドラインがあります。
- 効率性: Scikit-learnは、PythonのNumPyとSciPyという2つの強力なライブラリを基盤としています。これらのライブラリは高度に最適化されており、数学的な計算を効率的に行うことができます。
- 柔軟性: Scikit-learnは、プリプロセッシング、特徴選択、特徴抽出など、機械学習ワークフローの各ステップに役立つツールを提供します。
- コミュニティ: Scikit-learnは世界中のコミュニティに支持されており、新しい機能の開発や問題の解決が頻繁に行われています。

---

### 🌐 参考サイト
#### [【Python入門】7-2. scikit-learnライブラリ](https://utokyo-ipp.github.io/7/7-2.html)

---

### 🐣 はじめてみよう
- Pandasはデータサイエンティストや機械学習エンジニアが日々の仕事でよく利用するツールであり、Pythonでデータ分析を行う際には必須のライブラリとなっています。
- Scikit-learnは機械学習を扱うデータサイエンティストや研究者にとって、強力で信頼性の高いツールとなっています。
- 今回の講義では、このPandasとScikit-learnを使った機械学習について学んでいきましょう。

### ⬇️ ライブラリのインストール

In [ ]:
# matplotlib日本語対応ライブラリのインストール
!pip install matplotlib-fontja

### 📁 GoogleDrive の Mount

In [ ]:
# drive.mount()を使用してGoogleDriveをMount
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# os.chdir()を使用してカレントディレクトリを変更。作成したショートカット名を使ってパスを指定します。
import os
os.chdir('/content/drive/MyDrive/＜作成したショートカット名＞')

### ➜]　ライブラリのimport

In [1]:
import pandas as pd # pandasモジュールを読み込む（データ分析ライブラリ）
import numpy as np # NumPyモジュールを読み込む（数値演算ライブラリ）
import matplotlib.pyplot as plt # matplotlib.pyplot モジュールを読み込む（可視化ライブラリ。細かいカスタマイズが可能）
import seaborn as sns # Seabornモジュールを読み込む（可視化ライブラリ。pairplotなど多くのデータ分析情報をplotするのに向いている）
import joblib # モデル保存・読み込みライブラリ

from sklearn import svm # scikit-learnのSVM(サポートベクターマシン)
from sklearn.model_selection import train_test_split # scikit-learnの訓練データ / テストデータ 分割ライブラリ
from sklearn import metrics # scikit-learnの精度算出用ライブラリ
from sklearn.ensemble import RandomForestClassifier # scikit-learnのRandomForest(ランダムフォレスト)

from imblearn.over_sampling import SMOTE  # 不均衡データサンプリングライブラリ
from mpl_toolkits.axes_grid1 import Divider, Size # matplotlib 領域修正用クラス
from mpl_toolkits.axes_grid1.mpl_axes import Axes # matplotlib 領域修正用クラス

### ✍️ 定数の定義
- データファイルパスを定義しておきます
- データ読み込みの際にご使用してください。修正は不要です

In [2]:
# データファイルパス定義
WINE_CSV = "./data/wine.csv"
IRIS_CSV = "./data/iris.csv"

# モデルファイルパス定義
WINE_SVC_MODEL = "./data/wine_svc.joblib"
IRIS_SVC_MODEL = "./data/iris_svc.joblib"

# RANDOM SEED 定義
RANDOM_SEED = 0

### 🍾 サンプルプログラム1 ワイン分類モデルの学習

以下の手順で、ワインの分類モデルを学習します。
- ワインのデータセットを読み込む
- 読み込んだDataFrameを確認する
- SVCを用いて分類モデルを学習する
- 学習したモデルをjoblib.dump()でファイルに保存する(WINE_SVC_MODELで定義済みのファイル名を使用する)

In [3]:
# ワインのデータセットを読み込み
df_wine = pd.read_csv(WINE_CSV, index_col=None) # indexに使用するカラムが無いため、index_col=Noneを指定します

In [4]:
# 読み込んだDataFrameを確認
# 先頭5行を表示
df_wine.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [5]:
# データ型の表示
df_wine.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    int64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    int64
 13  target                        178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [6]:
# describe() 要約統計量の表示
df_wine.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,1.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,1.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,1.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,2.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,3.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,3.000000

In [7]:
# value_counts() ユニークな要素の抽出と出現頻度の表示
df_wine.target.value_counts()

target
2    71
1    59
3    48
Name: count, dtype: int64

In [8]:
# SVCで分類モデルを作る
# 説明変数と目的変数に分ける
X = df_wine.iloc[:,:-1]
y = df_wine.iloc[:,-1]

In [9]:
# 訓練データとテストデータに分割する
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_SEED) # 特に理由がない限りは、学習データ：テストデータは 7：3 でわけましょう。
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=RANDOM_SEED, stratify=y)  # stratifyを指定すると層別にきれいに分けることができます

In [10]:
# 学習する
svc_model = svm.SVC()    # モデルを作る
svc_model.fit(X_train, y_train)    # 訓練する

SVC()

In [11]:
# 学習したモデルを保存する
joblib.dump(svc_model, WINE_SVC_MODEL)

['./data/wine_svc.joblib']

### 🪻 練習プログラム1 あやめ分類モデルの学習 (25点)

以下の手順で、あやめの分類モデルを学習してみましょう。  
1️⃣ あやめのデータセットを読み込む   
2️⃣ 読み込んだDataFrameを確認する  
3️⃣ SVCを用いて分類モデルを学習する  
4️⃣ 学習したモデルをjoblib.dump()でファイルに保存する(IRIS_SVC_MODELで定義済みのファイル名を使用する)  

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# あやめのデータセットを読み込み

In [ ]:
# 読み込んだDataFrameを確認

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# データ型の表示

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [ ]:
# 要約統計量の表示

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [ ]:
# ユニークな要素の抽出と出現頻度の表示

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
# SVCで分類モデルを作る
# 説明変数と目的変数に分ける

In [ ]:
# 訓練データとテストデータに分割する

In [ ]:
# 学習する

SVC()

In [ ]:
# 学習したモデルを IRIS_SVC_MODEL に保存する

['./data/iris_svc.joblib']

In [ ]:
#@title 送信処理用共通プログラム（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown 解答の送信に必要です。（中身は絶対に修正しないでください）

import os
os.makedirs(".client/python", exist_ok=True)  # 隠しフォルダを作成
!wget -q https://raw.githubusercontent.com/YasuharuSuzuki/26_programing2/main/91_notebook_client/src/setup.sh -O .client/setup.sh   # 外部コードをダウンロードして隠しフォルダに配置
!chmod +x ./.client/setup.sh
!bash ./.client/setup.sh # 実行

# モジュールの初期化
exec(open('.client/client_setup.py').read())

# ノートブック固有の設定
NOTEBOOK_PATH = "13_機械学習(分類)/01_SVCによる分類モデルの学習.ipynb"
set_notebook_config(NOTEBOOK_PATH)

In [ ]:
#@title 問1 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=1, button_name="練習プログラム"))